version: "2"

linters:
  enable:
    - sloglint
    - usetesting
  settings:
    sloglint:
      context: scope
      forbidden-keys:
        - level
        - msg
        - time
      key-naming-case: snake
      no-global: all
    usetesting:
      os-create-temp: false
      os-mkdir-temp: false
      os-setenv: false
      os-temp-dir: false
      os-chdir: false
      context-background: true
      context-todo: false
