FROM microsoft/windowsservercore:latest   

#ENV chocolateyVersion 0.10.3
ENV ChocolateyUseWindowsCompression false

# Set your PowerShell execution policy
RUN powershell Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force

# Install Chocolatey
RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

# Install Chocolatey packages
RUN choco install -y git.install -params '"/GitAndUnixToolsOnPath"' && \
  choco install -y openssh && \
  choco install -y golang

# Copy across the agent source
ENV GOPATH=c:/gopath
WORKDIR c:/gopath/src/github.com/buildkite/agent
COPY . .

# Build agent
RUN go build -v -i -o c:/gopath/bin/buildkite-agent.exe

CMD ["c:/gopath/bin/buildkite-agent.exe", "start"]
