[tools]
go = "1.26.5"
golangci-lint = "2.9.0"
ruby = "3.4.9"

[bootstrap.packages]
"apt:autoconf" = "latest"
"apt:bison" = "latest"
"apt:build-essential" = "latest"
"apt:ca-certificates" = "latest"
"apt:curl" = "latest"
"apt:git" = "latest"
"apt:libdb-dev" = "latest"
"apt:libffi-dev" = "latest"
"apt:libgdbm-dev" = "latest"
"apt:libgmp-dev" = "latest"
"apt:libncurses-dev" = "latest"
"apt:libreadline-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:libyaml-dev" = "latest"
"apt:patch" = "latest"
"apt:uuid-dev" = "latest"
"apt:zlib1g-dev" = "latest"

[tasks.test]
description = "Run automated tests"
run = "go tool gotestsum --format pkgname --"

[tasks.lint]
description = "Run formatting and lint checks"
run = [
  "go tool gofumpt -extra -w .",
  "golangci-lint run",
]
