FROM golang:1.20.6@sha256:010a0ffe47398a3646993df44906c065c526eabf309d01fb0cbc9a5696024a60
COPY build/ssh.conf /etc/ssh/ssh_config.d/
RUN go install github.com/google/go-licenses@latest

# Ruby used for polyglot hook integration tests
RUN apt update && apt install -y ruby
