FROM public.ecr.aws/docker/library/alpine:3.18.4@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978

# We need buildkite-agent to download artifacts, and zip for Windows zipping
RUN apk --no-cache add bash zip curl \
    && curl -o /usr/bin/buildkite-agent https://download.buildkite.com/agent/stable/latest/buildkite-agent-linux-amd64 \
    && chmod +x /usr/bin/buildkite-agent
