FROM public.ecr.aws/docker/library/golang:1.27.0@sha256:4013ae0f9e7994f8535c58c811f8f863fbed38b72e0d51e6592156f758d66146
COPY build/ssh.conf /etc/ssh/ssh_config.d/

COPY go-licenses-version /tmp/go-licenses-version
RUN go install "github.com/google/go-licenses@$(cat /tmp/go-licenses-version)"
# Ruby used for polyglot hook integration tests
RUN apt update && apt install -y ruby
