FROM public.ecr.aws/docker/library/alpine:3.20.0@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd

# We need buildkite-agent to download artifacts, and zip for Windows zipping
RUN apk --no-cache add bash zip curl \
    && curl -o /usr/bin/buildkite-agent https://download.buildkite.com/agent/stable/latest/buildkite-agent-linux-amd64 \
    && chmod +x /usr/bin/buildkite-agent
