FROM public.ecr.aws/docker/library/alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

# We need buildkite-agent to download artifacts, and zip for Windows zipping
RUN apk --no-cache add bash zip curl \
    && curl -o /usr/bin/buildkite-agent https://download.buildkite.com/agent/stable/latest/buildkite-agent-linux-amd64 \
    && chmod +x /usr/bin/buildkite-agent
