FROM public.ecr.aws/docker/library/golang:1.22.5@sha256:fcae9e0e7313c6467a7c6632ebb5e5fab99bd39bd5eb6ee34a211353e647827a
COPY build/ssh.conf /etc/ssh/ssh_config.d/

RUN go install github.com/google/go-licenses@latest
# Ruby used for polyglot hook integration tests
RUN apt update && apt install -y ruby
