version: '2'

services:

  github-release:
    build:
      context: .
      dockerfile: Dockerfile-github-release
    volumes:
      - ../:/app
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
    working_dir: /app
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER

  # Used by the publishing steps in pipeline.release-*.yml
  release:
    build:
      context: .
      dockerfile: Dockerfile-release
    volumes:
      - ../:/workdir
      # Scratch space for the yum repo in publish-rpm-package.sh
      - /yum.buildkite.com
    # publish-debian-package.sh refuses to import signing keys unless this is tmpfs
    tmpfs:
      - /root/.gnupg:mode=0700
    working_dir: /workdir
