steps:
  - wait

  - name: ":s3: Publish Edge Binaries"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "experimental"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":redhat: Publish Edge RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "experimental"
      RPM_S3_BUCKET: "yum.buildkite.com"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
      - docker#v5.8.0:
          image: "buildkite/agent:3.55.0-ubuntu"
          entrypoint: bash
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          propagate-environment: true
          mount-buildkite-agent: true
          volumes:
            - "/yum.buildkite.com"

  - name: ":redhat: Publish Edge RPM Package to Buildkite Packages"
    command: ".buildkite/steps/publish-buildkite-packages.sh"
    env:
      REGISTRY: "buildkite/agent-rpm-experimental"
      EXTENSION: rpm
    soft_fail: true

  - name: ":debian: Publish Edge Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "experimental"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
          tmpfs:
            - "/root/.gnupg"
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - name: ":debian: Publish Edge Debian Package to Buildkite Packages"
    command: ".buildkite/steps/publish-buildkite-packages.sh"
    env:
      REGISTRY: "buildkite/agent-deb-experimental"
      EXTENSION: deb
    soft_fail: true

  - name: ":docker: Publish Edge Docker Images"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "experimental"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
      - ecr#v2.7.0:
          login: true
          account-ids: "445615400570"
