steps:
  -
    name: "🔨"
    command: "scripts/tests.sh"
    plugins:
      - https://github.com/buildkite/docker-compose-buildkite-plugin#8b2d39c:
          run: agent

  -
    name: "📦"
    command: "scripts/build-binaries.sh"
    artifact_paths: "pkg/*"
    plugins:
      - https://github.com/buildkite/docker-compose-buildkite-plugin#8b2d39c:
          run: agent

  - wait

  -
    name: ":debian: build"
    command: "scripts/build-debian-packages.sh"
    artifact_paths: "deb/**/*"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":redhat: experimental"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master *-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish experimental"
    command: "scripts/publish-debian-package.sh"
    branches: "master *-stable"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":github: :hammer:"
    command: "scripts/build-github-release.sh"
    artifact_paths: "releases/**/*"
    branches: "master *-stable"
    plugins:
      - https://github.com/buildkite/docker-compose-buildkite-plugin#8b2d39c:
          run: agent

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master *-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Unstable"
    branches: "master *-stable"

  -
    name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    branches: "master *-stable"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master *-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish unstable"
    command: "scripts/publish-debian-package.sh"
    branches: "master *-stable"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master *-stable"
    agents:
      queue: "deploy"

  -
    name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    branches: "master *-stable"
    agents:
      queue: "deploy"

  - block: ":shipit: Stable"
    branches: "master *-stable"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master *-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":debian: publish stable"
    command: "scripts/publish-debian-package.sh"
    branches: "master *-stable"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master *-stable"
    agents:
      queue: "deploy"
