env:
  DRY_RUN: false # set to true to disable publishing releases

steps:
  - name: ":hammer: :linux:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":hammer: :windows:"
    trigger: agent-windows
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - name: ":windows: 386"
    command: ".buildkite/steps/build-binary.sh windows 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":windows: amd64"
    command: ".buildkite/steps/build-binary.sh windows amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":linux: amd64"
    command: ".buildkite/steps/build-binary.sh linux amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":linux: 386"
    command: ".buildkite/steps/build-binary.sh linux 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":linux: arm"
    command: ".buildkite/steps/build-binary.sh linux arm"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":linux: armhf"
    command: ".buildkite/steps/build-binary.sh linux armhf"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":linux: arm64"
    command: ".buildkite/steps/build-binary.sh linux arm64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":mac: 386"
    command: ".buildkite/steps/build-binary.sh darwin 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":mac: amd64"
    command: ".buildkite/steps/build-binary.sh darwin amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":freebsd: amd64"
    command: ".buildkite/steps/build-binary.sh freebsd amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":freebsd: 386"
    command: ".buildkite/steps/build-binary.sh freebsd 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":openbsd: amd64"
    command: ".buildkite/steps/build-binary.sh openbsd amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":openbsd: 386"
    command: ".buildkite/steps/build-binary.sh openbsd 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - name: ":dragonflybsd: amd64"
    command: ".buildkite/steps/build-binary.sh dragonfly amd64"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - wait

  - name: ":mag:"
    command: ".buildkite/steps/extract-agent-version-metadata.sh"

  - wait

  - name: ":docker: build"
    command: ".buildkite/steps/build-docker-images.sh"

  - name: ":debian: build"
    command: ".buildkite/steps/build-debian-packages.sh"
    artifact_paths: "deb/**/*"
    agents:
      queue: "deploy"

  - name: ":redhat: build"
    command: ".buildkite/steps/build-rpm-packages.sh"
    artifact_paths: "rpm/**/*"
    agents:
      queue: "deploy"

  - name: ":github: :hammer:"
    command: ".buildkite/steps/build-github-release.sh"
    artifact_paths: "releases/**/*"
    plugins:
      docker-compose#v1.8.0:
        config: docker-compose.release.yml
        run: github-release

  - wait

  - name: ":pipeline:"
    command: ".buildkite/steps/upload-release-steps.sh"
