agents:
  queue: agent-runners-linux-amd64

env:
  CI_E2E_TESTS_TARGET_ORG: agent-e2e-testing
  CI_E2E_TESTS_TARGET_CLUSTER: e1773a06-b43c-4b77-84e5-5e088a737f6a

steps:
  - label: ":go::sleuth_or_spy: Run agent end-to-end tests"
    command: .buildkite/steps/e2e-tests.sh
    secrets:
      - CI_E2E_TESTS_BUILDKITE_API_TOKEN
      - CI_E2E_TESTS_AGENT_TOKEN
    plugins:
      - docker-compose#v4.14.0:
          config: .buildkite/docker-compose.yml
          cli-version: 2
          mount-buildkite-agent: true
          run: e2e
