steps:
  - wait

  - name: ":s3: Publish Edge Binaries"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "experimental"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - docker-compose#v5.15.0:
          config: .buildkite/docker-compose.release.yml
          run: release
          mount-buildkite-agent: true
          propagate-environment: true
          propagate-aws-auth-tokens: true

  - name: ":redhat: Publish Edge RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "experimental"
      RPM_S3_BUCKET: "yum.buildkite.com"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - docker-compose#v5.15.0:
          config: .buildkite/docker-compose.release.yml
          run: release
          mount-buildkite-agent: true
          propagate-environment: true
          propagate-aws-auth-tokens: true

  - name: ":debian: Publish Edge Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "experimental"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - docker-compose#v5.15.0:
          config: .buildkite/docker-compose.release.yml
          run: release
          mount-buildkite-agent: true
          propagate-environment: true
          propagate-aws-auth-tokens: true
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - group: ":docker: Publish Edge Docker Images"
    steps:
      - name: ":docker: Publish Edge Images to {{matrix.registry}}"
        command: ".buildkite/steps/publish-docker-images.sh"
        env:
          CODENAME: "experimental"
          REGISTRY: "{{matrix.registry}}"
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-edge
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
                - build_branch
          - ecr#v2.7.0:
              login: true
              account-ids: "445615400570"
        matrix:
          setup:
            registry:
              - docker.io
              - ghcr.io
              - packages.buildkite.com
          adjustments:
            - with: { registry: "packages.buildkite.com" }
              soft_fail: true
