steps:
  - wait

  - name: ":spiral_note_pad: Check Changelog"
    command: ".buildkite/steps/check-changelog.sh"

  - wait

  - name: ":s3: Upload Binaries to S3"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true

  - name: ":octocat: :rocket: Create Github Release (if necessary)"
    command: ".buildkite/steps/github-release.sh"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true

  - name: ":redhat: Publish RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "stable"
      RPM_S3_BUCKET: "yum.buildkite.com"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true
          volumes:
            - "/yum.buildkite.com"

  - name: ":debian: Publish Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "stable"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true
          tmpfs:
            - "/root/.gnupg"

  - name: ":docker: Publish Docker Images"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "445615400570"

  - wait

  - name: ":beer: Publish Homebrew Package"
    command: ".buildkite/steps/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.0.0:
          login: true
          account-ids: "032379705303"
      - docker#v3.5.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2020.03"
          propagate-environment: true
