steps:
  - name: ":spiral_note_pad: Check Changelog"
    command: ".buildkite/steps/check-changelog.sh"
    key: "check_changelog"

  - name: ":s3: Upload Binaries to S3"
    key: "upload_binaries_to_s3"
    depends_on:
      - "check_changelog"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":octocat: :rocket: Create Github Release (if necessary)"
    key: "create_github_release_if_necessary"
    depends_on:
      - "check_changelog"
    command: ".buildkite/steps/github-release.sh"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":redhat: Publish RPM Package"
    key: "publish_rpm_package"
    depends_on:
      - "check_changelog"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "stable"
      RPM_S3_BUCKET: "yum.buildkite.com"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "buildkite/agent:3.55.0-ubuntu"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
          volumes:
            - "/yum.buildkite.com"
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - group: ":redhat: Publish RPM Package to Buildkite Packages"
    key: "publish_rpm_package_to_buildkite_packages"
    depends_on:
      - "check_changelog"
    steps:
      - name: ":redhat: Publish {{matrix.pkg_arch}} RPM Package to Buildkite Packages"
        plugins:
          - publish-to-packages#v2.2.0:
              artifacts: "rpm/buildkite-agent_*_{{matrix.pkg_arch}}.rpm"
              registry: "buildkite/agent-rpm"
              artifact_build_id: "${BUILDKITE_TRIGGERED_FROM_BUILD_ID}"
              attestations:
                - "buildkite-agent-linux-{{matrix.go_arch}}.build-attestation.json"
                - "buildkite-agent-rpm-packages.package-attestation.json"
        soft_fail: true
        matrix:
          setup:
            go_arch:
              - "amd64"
              - "386"
              - "arm64"
              - "ppc64"
              - "ppc64le"
              - "riscv64"
            pkg_arch:
              - "SKIP_FAKE_ARCH"
          adjustments:
            - with: { go_arch: "amd64", pkg_arch: "x86_64" }
            - with: { go_arch: "386", pkg_arch: "i386" }
            - with: { go_arch: "arm64", pkg_arch: "aarch64" }
            - with: { go_arch: "ppc64", pkg_arch: "ppc64" }
            - with: { go_arch: "ppc64le", pkg_arch: "ppc64le" }
            - with: { go_arch: "riscv64", pkg_arch: "riscv64" }
            - with: { pkg_arch: "SKIP_FAKE_ARCH" }
              skip: true

  - name: ":debian: Publish Debian Package"
    key: "publish_debian_package"
    depends_on:
      - "check_changelog"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "stable"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
          tmpfs:
            - "/root/.gnupg"

  - group: ":debian: Publish Debian Package to Buildkite Packages"
    key: "publish_debian_package_to_buildkite_packages"
    depends_on:
      - "check_changelog"
    steps:
      - name: ":debian: Publish {{matrix.pkg_arch}} Debian Package to Buildkite Packages"
        plugins:
          - publish-to-packages#v2.2.0:
              artifacts: "deb/buildkite-agent_*_{{matrix.pkg_arch}}.deb"
              registry: "buildkite/agent-deb"
              artifact_build_id: "${BUILDKITE_TRIGGERED_FROM_BUILD_ID}"
              attestations:
                - "buildkite-agent-linux-{{matrix.go_arch}}.build-attestation.json"
                - "buildkite-agent-debian-packages.package-attestation.json"
        soft_fail: true
        matrix:
          setup:
            go_arch:
              - "amd64"
              - "386"
              - "arm"
              - "armhf"
              - "arm64"
              - "ppc64"
              - "ppc64le"
              - "riscv64"
            pkg_arch:
              - "SKIP_FAKE_ARCH"
          adjustments:
            - with: { go_arch: "amd64", pkg_arch: "x86_64" }
            - with: { go_arch: "386", pkg_arch: "i386" }
            - with: { go_arch: "arm", pkg_arch: "arm" }
            - with: { go_arch: "armhf", pkg_arch: "armhf" }
            - with: { go_arch: "arm64", pkg_arch: "arm64" }
            - with: { go_arch: "ppc64", pkg_arch: "ppc64" }
            - with: { go_arch: "ppc64le", pkg_arch: "ppc64el" }
            - with: { go_arch: "riscv64", pkg_arch: "riscv64" }
            - with: { pkg_arch: "SKIP_FAKE_ARCH" }
              skip: true

  - group: ":docker: Publish Docker Images"
    key: "publish_docker_images"
    depends_on:
      - "check_changelog"
    steps:
      - name: ":docker: Publish Docker Images to {{matrix.registry}}"
        command: ".buildkite/steps/publish-docker-images.sh"
        env:
          CODENAME: "stable"
          REGISTRY: "{{matrix.registry}}"
        plugins:
          - aws-assume-role-with-web-identity#v1.4.0:
              role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
              session-tags:
                - organization_slug
                - organization_id
                - pipeline_slug
                - build_branch
          - ecr#v2.7.0:
              login: true
              account-ids: "445615400570"
        matrix:
          setup:
            registry:
              - docker.io
              - ghcr.io
              - packages.buildkite.com
          adjustments:
            - with: { registry: "packages.buildkite.com" }
              soft_fail: true

  - name: ":beer: Publish Homebrew Package"
    depends_on:
      - "upload_binaries_to_s3"
      - "create_github_release_if_necessary"
      - "publish_rpm_package"
      - "publish_rpm_package_to_buildkite_packages"
      - "publish_debian_package"
      - "publish_debian_package_to_buildkite_packages"
    command: ".buildkite/steps/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
