steps:
  - wait

  - name: ":spiral_note_pad: Check Changelog"
    command: ".buildkite/steps/check-changelog.sh"

  - wait

  - name: ":s3: Upload Binaries to S3"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":octocat: :rocket: Create Github Release (if necessary)"
    command: ".buildkite/steps/github-release.sh"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":redhat: Publish RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "stable"
      RPM_S3_BUCKET: "yum.buildkite.com"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "buildkite/agent:3.55.0-ubuntu"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
          volumes:
            - "/yum.buildkite.com"
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - name: ":redhat: Publish RPM Package to Packagecloud"
    command: ".buildkite/steps/publish-rpm-packagecloud.sh"
    env:
      REPOSITORY: "buildkite/agent-rpm"
      DISTRO_VERSION: rpm_any/rpm_any
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":redhat: Publish RPM Package to Buildkite Packages"
    command: ".buildkite/steps/publish-rpm-buildkite-packages.sh"
    env:
      REPOSITORY: "buildkite/agent-rpm"
    agents:
      queue: "deploy"
    plugins:
      - docker#v5.8.0:
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":debian: Publish Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "stable"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
          tmpfs:
            - "/root/.gnupg"

  - name: ":debian: Publish Debian Package to Buildkite Packages"
    command: ".buildkite/steps/publish-debian-buildkite-packages.sh"
    env:
      REPOSITORY: "buildkite/agent-deb"
    agents:
      queue: "deploy"
    plugins:
      - docker#v5.8.0:
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":debian: Publish Debian Package to Packagecloud"
    command: ".buildkite/steps/publish-debian-packagecloud.sh"
    env:
      REPOSITORY: "buildkite/agent-deb"
      DISTRO_VERSION: any/any
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":docker: Publish Docker Images"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - ecr#v2.7.0:
          login: true
          account-ids: "445615400570"

  - wait

  - name: ":beer: Publish Homebrew Package"
    command: ".buildkite/steps/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    env:
      CODENAME: "stable"
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::032379705303:role/pipeline-buildkite-agent-release-stable
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          environment:
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_SESSION_TOKEN"
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
