env:
  DRY_RUN: false # set to true to disable publishing releases
agents:
  queue: agent-runners-linux-amd64

steps:
  - name: ":windows: Windows AMD64 Tests"
    key: test-windows1
    command: "bash .buildkite\\steps\\tests.sh"
    artifact_paths: junit-*.xml
    agents:
      queue: agent-runners-windows-amd64
    plugins:
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"
      - artifacts#v1.9.0:
          upload: "cover.{html,out}"

  - name: ":windows: Windows AMD64 Tests"
    key: test-windows2
    command: "bash .buildkite\\steps\\tests.sh"
    artifact_paths: junit-*.xml
    agents:
      queue: agent-runners-windows-amd64
    plugins:
      - test-collector#v1.2.0:
          files: "junit-*.xml"
          format: "junit"
      - artifacts#v1.9.0:
          upload: "cover.{html,out}"
