#!/bin/bash
set -e
set -x

mkdir -p pkg

build() {
  FILENAME=buildbox-agent-$GOOS-$GOARCH
  go build -o pkg/$FILENAME
  tar -cvzf pkg/$FILENAME.tar.gz pkg/$FILENAME
  rm pkg/$FILENAME
}

GOOS=linux
GOARCH=amd64 build
GOARCH=386 build

# --

GOOS=darwin
GOARCH=amd64 build
GOARCH=386 build
